name: partner
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.5.4
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  dio: ^5.3.0
  fluttertoast: ^8.1.2
  shared_preferences: ^2.0.15
  cached_network_image: ^3.3.0
#  image_cropper: ^8.0.2
  get: ^4.6.6
  pretty_dio_logger: ^1.3.1
  flutter_bloc: ^8.1.2
  location:
  skeletonizer: ^2.0.1
  permission_handler: ^11.0.1
  go_router: ^14.2.7
  dropdown_search: ^5.0.6
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.4.0
  path_provider: ^2.0.13
  flutter_widget_from_html: ^0.15.3
  google_nav_bar: ^5.0.7
  firebase_messaging: ^15.2.1
  firebase_core: ^3.10.1
  firebase_database: ^11.3.1
  flutter_local_notifications: ^19.2.1
  liquid_pull_to_refresh: ^3.0.1
  card_swiper: ^3.0.1
  image_picker: ^1.1.2
  dotted_border: ^3.0.1
  flutter_image_compress: ^2.4.0

dev_dependencies:
  #flutter packages pub run build_runner build
  build_runner: any
  flutter_gen_runner: ^5.7.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:


  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: InterBlack
      fonts:
        - asset: assets/fonts/Inter-Black.ttf

    - family: InterBold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf

    - family: InterExtraBold
      fonts:
        - asset: assets/fonts/Inter-ExtraBold.ttf

    - family: InterExtraLight
      fonts:
        - asset: assets/fonts/Inter-ExtraLight.ttf

    - family: InterLight
      fonts:
        - asset: assets/fonts/Inter-Light.ttf

    - family: InterMedium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf

    - family: InterRegular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf

    - family: InterSemiBold
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf

    - family: InterThin
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf